version: "3.9"

services:
  flask:
      container_name: flask
      command: "gunicorn app:app --bind 0.0.0.0:8000 --reload"
      build: .
      restart: unless-stopped
      env_file:
        - .env
      volumes:
        - ./src:/app

  nginx:
    image: nginx:stable-alpine
    container_name: nginxportfolio
    restart: unless-stopped
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - 8000:8000
    depends_on:
      - flask